import { Inter } from "next/font/google";
import "../../globals.css";
import AdminHeader from "@/app/(admin)/admin/components/AdminHeader";
import Link from "next/link";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AdminHeader/>

        <div className="flex">
          <div className="w-1/4">
            <div className="flex flex-col">
                <Link href="/admin" className="text-slate-600 hover:bg-slate-600 hover:text-slate-200 bg-slate-200 py-3 px-4">Dashboard</Link>
                <Link href="" className="text-slate-600 hover:bg-slate-600 hover:text-slate-200 bg-slate-200 py-3 px-4">Manage Users</Link>
                <Link href="/admin/categories" className="text-slate-600 hover:bg-slate-600 hover:text-slate-200 bg-slate-200 py-3 px-4">Manage Categories</Link>
                <Link href="/admin/juices" className="text-slate-600 hover:bg-slate-600 hover:text-slate-200 bg-slate-200 py-3 px-4">Manage juices</Link>
                <Link href="" className="text-slate-600 hover:bg-slate-600 hover:text-slate-200 bg-slate-200 py-3 px-4">Manage Orders</Link>
                <Link href="" className="text-slate-600 hover:bg-slate-600 hover:text-slate-200 bg-slate-200 py-3 px-4">Manage Payments</Link>
                <Link href="" className="text-slate-600 hover:bg-slate-600 hover:text-slate-200 bg-slate-200 py-3 px-4">Logout</Link>
            </div>
          </div>
          <div className="w-3/4">
             {children}
             <Toaster position="top-right"/>
          </div>
        </div>
        </body>
    </html>
  );
}
